### ISSUE TITLE
An error occurred while compiling for arm Linux

### ISSUE THREAD

**Issue by Luupw3d** [X-Ryl669/MJPGServer#1]
Hi！I tried to build this project  for my **Raspberry 4B (arm v7)**，but occurred a error:

>  Computing dependencies for V4L2Source.cpp
>  Computing dependencies for MJPGServer.cpp
>  Compiling MJPGServer.cpp
>  Compiling V4L2Source.cpp
>  Compiling Threads.cpp into ClassPath/Threading/
>  Compiling Lock.cpp into ClassPath/Threading/
/tmp/ccNHhirf.s: Assembler messages:
/tmp/ccNHhirf.s:3382: Error: selected processor does not support \`yield' in ARM mode
/tmp/ccNHhirf.s:3409: Error: selected processor does not support \`yield' in ARM mode
make: *** [Makefile:78: ClassPath/Threading/Lock.o] Error 1

make --version ：GNU Make 4.2.1
gcc -v :gcc version 8.3.0 (Raspbian 8.3.0-6+rpi1)

Thanks!

**Comment by X-Ryl669** [comment]
It's strange. From a google search, it seems like a compilation flags is missing:
Can you replace the line 45 and 46 of `build/linux/Makefile` to:
```
CXXFLAGS += -pthread -march=native -mcpu=native
CFLAGS += -pthread -march=native -mcpu=native
``` 

And try building again (`make clean && make`) ?

**Comment by Luupw3d** [comment]
I have modified the line 45 and 46 like the sample you provided.The old errors disappeared  but a new error occurred :
>  Compiling Time.cpp into ClassPath/Time/
>  Compiling Socket.cpp into ClassPath/Network/
>  Compiling Server.cpp into ClassPath/Network/
>  Compiling Connection.cpp into ClassPath/Network/
>  Compiling Address.cpp into ClassPath/Network/
>  Compiling HTTP.cpp into ClassPath/Network/Servers/
>  Compiling AES.cpp into ClassPath/Crypto/
>  Compiling HTTPCode.cpp into ClassPath/Protocol/HTTP/
>  Compiling TextualHeaders.cpp into ClassPath/Network/Clients/
>  Compiling LinuxSpecific.cpp into ClassPath/Network/
>  Compiling Random.cpp into ClassPath/Crypto/
>  Compiling bstrlib.c into ClassPath/Strings/BString/
Linking mjpgsrv
/usr/bin/ld: cannot find -lbfd
collect2: error: ld returned 1 exit status
make: *** [Makefile:59: mjpgsrv] Error 1

**Comment by X-Ryl669** [comment]
Can you pull the repository again, and confirm it's fixed for you ? Thanks!

**Comment by Luupw3d** [comment]
The problems were fixed！ And after reading the [GCC documentation](https://gcc.gnu.org/onlinedocs/), I think it is a better choice to use **-mcpu=name** instead of **-march** and **-mtune** when the CPU model is known. Of course, this only applies to devices with a certain CPU model, such as Raspberry Pi 4.
>This specifies the name of the target ARM processor. GCC uses this name to derive the name of the target ARM architecture (as if specified by -march)and the ARM processor type for which to tune for performance (as if specified by -mtune). Where this option is used in conjunction with -marchor -mtune, those options take precedence over the appropriate part of this option.
Permissible names for this option are the same as those for -mtune.

**Comment by X-Ryl669** [comment]
You're right, it's more logical. But then, GCC decided to emit a warning since version 10.0 when you use `mcpu=native` and instead ask you to use `mtune` instead. And since I don't want to add the autotool/automake mess here to detect the cpu, I'm using the less effort solution: use `mtune`. 

Thank you for your time!
